trigger:
  branches:
    include:
      - main
      - develop

variables:
  buildConfiguration: 'Release'

stages:

# -------------------
# CI - Build Stage
# -------------------
- stage: Build
  displayName: 'Build & Publish (.NET 8)'
  jobs:
    - job: Build
      displayName: 'Build Job'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Install .NET 8 SDK'
          inputs:
            packageType: 'sdk'
            version: '8.0.x'
            includePreviewVersions: true

        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet packages'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Build Solution'
          inputs:
            command: 'build'
            arguments: '--configuration $(buildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: 'Publish Artifacts'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact to Pipeline'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

# -------------------
# CD - Dev Deployment
# -------------------
- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Build
  jobs:
    - deployment: DeployDev
      environment: 'Development'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                displayName: 'Deploy to Azure Web App (Dev)'
                inputs:
                  azureSubscription: 'RamsanAzureServiceCon'
                  appType: 'webApp'
                  appName: 'HospitalQueueSystem'
                  package: '$(Pipeline.Workspace)/drop/**/*.zip'

# -------------------
# CD - QA Deployment
# -------------------
- stage: Deploy_QA
  displayName: 'Deploy to QA'
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
    - deployment: DeployQA
      environment: 'Staging'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                displayName: 'Deploy to Azure Web App (QA)'
                inputs:
                  azureSubscription: 'RamsanAzureServiceCon'
                  appType: 'webApp'
                  appName: 'HospitalQueueSystem'
                  package: '$(Pipeline.Workspace)/drop/**/*.zip'

# -------------------
# CD - Prod Deployment (with Approval)
# -------------------
- stage: Deploy_Prod
  displayName: 'Deploy to Prod'
  dependsOn: Deploy_QA
  condition: succeeded()
  jobs:
    - deployment: DeployProd
      environment: 'Production'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                displayName: 'Deploy to Azure Web App (Prod)'
                inputs:
                  azureSubscription: 'RamsanAzureServiceCon'
                  appType: 'webApp'
                  appName: 'HospitalQueueSystem'
                  package: '$(Pipeline.Workspace)/drop/**/*.zip'
